name: Generate Space Shooter

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # This ensures the full history is pulled so git can push changes
          fetch-depth: 0

      - name: generate-space-shooter-video
        uses: czl9707/gh-space-shooter@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          username: ${{ github.repository_owner }}
          output-path: space-shooter.gif
